high5 = resshape_data('./results/Highdifsl-ce4t5.result')
mid5 = resshape_data('./results/Middifsl-ce4t5.result')
low5 = resshape_data('./results/Lowdifsl-ce4t5.result')
high10 = resshape_data('./results/Highdifsl-ce4t10.result')
mid10 = resshape_data('./results/Middifsl-ce4t10.result')
low10 = resshape_data('./results/Lowdifsl-ce4t10.result')
high1 = resshape_data('./results/Highdifsl-ce4t1.result')
mid1 = resshape_data('./results/Middifsl-ce4t1.result')
low1 = resshape_data('./results/Lowdifsl-ce4t1.result')
high2 = resshape_data('./results/Highdifsl-ce4t2.result')
mid2 = resshape_data('./results/Middifsl-ce4t2.result')
low2 = resshape_data('./results/Lowdifsl-ce4t2.result')
with(low1[low1$time==8460,],plot(distance,Bicoid,'l',col='lightgreen'))
with(mid1[mid1$time==8460,],lines(distance,Bicoid,'l',col='green'))
with(high1[high1$time==8460,],lines(distance,Bicoid,'l',col='darkgreen'))
with(low2[low2$time==8460,],lines(distance,Bicoid,'l',col='orchid'))
with(mid2[mid2$time==8460,],lines(distance,Bicoid,'l',col='mediumorchid'))
with(high2[high2$time==8460,],lines(distance,Bicoid,'l',col='darkorchid'))
with(low5[low5$time==8460,],lines(distance,Bicoid,'l',col='lightblue'))
with(mid5[mid5$time==8460,],lines(distance,Bicoid,'l',col='blue'))
with(high5[high5$time==8460,],lines(distance,Bicoid,'l',col='darkblue'))
with(low10[low10$time==8460,],lines(distance,Bicoid,'l',col='pink'))
with(mid10[mid10$time==8460,],lines(distance,Bicoid,'l',col='red'))
with(high10[high10$time==8460,],lines(distance,Bicoid,'l',col='darkred'))
for(model in c(high10,mid10,low10,high5,mid5,low5,high2,mid2,low2,high1,mid1,low1)){
  wireframe(Bicoid ~ distance * time,model,drape=TRUE,shade=T,pretty=T,scales = list(arrows=FALSE, col = "black"))
}